import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Deliberately unauthenticated — same reasoning as the bare health endpoint:
// a host bootstrapping the agent for the first time has no session cookie
// yet, and none of this is sensitive on its own (the binary is identical
// for every host; the actual credential is the agent key the admin pastes
// in when running the command, generated separately behind auth in
// routes/hosts.ts). Not to be confused with /api/agent/*, which the
// already-installed agent itself calls and which IS key-authenticated.
export const installRouter = Router();

const repoRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const agentDir = path.join(repoRoot, "agent");

const PLATFORM_FILES: Record<string, string> = {
  "linux-amd64": "looksee-agent-linux-amd64",
  "linux-arm64": "looksee-agent-linux-arm64",
  "windows-amd64": "looksee-agent-windows-amd64.exe",
  "darwin-amd64": "looksee-agent-darwin-amd64",
  "darwin-arm64": "looksee-agent-darwin-arm64",
};

function publicUrl(): string {
  return process.env.PUBLIC_URL ?? `http://localhost:${process.env.PORT ?? 4100}`;
}

// GET /install/agent.sh
// The one command shown in the dashboard after generating a host's agent
// key: `curl -fsSL <engine>/install/agent.sh | sudo bash -s -- <key>`.
// Detects OS/arch, downloads the matching binary and this same engine's
// install.sh + systemd unit (so there's exactly one authored copy of the
// actual install logic, not a duplicate reimplemented here), and runs it.
installRouter.get("/agent.sh", (_req, res) => {
  const url = publicUrl();
  const script = `#!/usr/bin/env bash
# Generated by Looksee — downloads and installs the monitoring agent.
# Usage: curl -fsSL ${url}/install/agent.sh | sudo bash -s -- <agent-key>
set -euo pipefail

AGENT_KEY="\${1:?Usage: curl -fsSL ${url}/install/agent.sh | sudo bash -s -- <agent-key>}"
ENGINE_URL="${url}"

OS="$(uname -s)"
ARCH="$(uname -m)"
case "$OS-$ARCH" in
  Linux-x86_64) PLATFORM=linux-amd64 ;;
  Linux-aarch64|Linux-arm64) PLATFORM=linux-arm64 ;;
  Darwin-x86_64) PLATFORM=darwin-amd64 ;;
  Darwin-arm64) PLATFORM=darwin-arm64 ;;
  *)
    echo "Unsupported platform: $OS $ARCH — see agent/README.md for a manual build/install." >&2
    exit 1
    ;;
esac

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> Downloading looksee-agent for $PLATFORM"
curl -fsSL "$ENGINE_URL/install/agent/$PLATFORM" -o "$WORK_DIR/looksee-agent"
chmod +x "$WORK_DIR/looksee-agent"

cat > "$WORK_DIR/looksee-agent.yaml" <<CFG
engine_url: "$ENGINE_URL"
agent_key: "$AGENT_KEY"
interval_seconds: 30
CFG

if [ "$OS" != "Linux" ]; then
  echo "Downloaded to $WORK_DIR — no automated service install for $OS yet."
  echo "Copy looksee-agent + looksee-agent.yaml somewhere permanent, then see"
  echo "agent/README.md for NSSM/Task Scheduler (Windows) or launchd (macOS)."
  exit 0
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "Binary + config ready in $WORK_DIR."
  echo "Re-run this same command with sudo to also install it as a systemd service."
  exit 0
fi

echo "==> Installing as a systemd service"
curl -fsSL "$ENGINE_URL/install/install.sh" -o "$WORK_DIR/install.sh"
curl -fsSL "$ENGINE_URL/install/looksee-agent.service" -o "$WORK_DIR/looksee-agent.service"
chmod +x "$WORK_DIR/install.sh"
(cd "$WORK_DIR" && ./install.sh looksee-agent looksee-agent.yaml)
`;
  res.type("text/x-shellscript").send(script);
});

// Serves this engine's own agent/install.sh and looksee-agent.service
// verbatim — the bootstrap script above downloads and runs these rather
// than duplicating their logic, so there's one source of truth.
installRouter.get("/install.sh", (_req, res) => {
  const filePath = path.join(agentDir, "install.sh");
  if (!fs.existsSync(filePath)) {
    res.status(404).send("install.sh not found on this engine.");
    return;
  }
  res.type("text/x-shellscript").sendFile(filePath);
});

installRouter.get("/looksee-agent.service", (_req, res) => {
  const filePath = path.join(agentDir, "looksee-agent.service");
  if (!fs.existsSync(filePath)) {
    res.status(404).send("looksee-agent.service not found on this engine.");
    return;
  }
  res.type("text/plain").sendFile(filePath);
});

// GET /install/agent/:platform — one of the keys in PLATFORM_FILES, e.g.
// linux-amd64. Binaries come from agent/bin/, populated by running
// agent/build-all.sh on this host at least once after cloning/updating.
installRouter.get("/agent/:platform", (req, res) => {
  const fileName = PLATFORM_FILES[req.params.platform];
  if (!fileName) {
    res.status(400).json({ error: `Unknown platform. Valid: ${Object.keys(PLATFORM_FILES).join(", ")}` });
    return;
  }
  const filePath = path.join(agentDir, "bin", fileName);
  if (!fs.existsSync(filePath)) {
    res
      .status(404)
      .send(`No built binary for ${req.params.platform} on this engine yet — run agent/build-all.sh on the server first.`);
    return;
  }
  res.download(filePath, fileName);
});
